### PR TITLE
fix(spaces nearby): get correctly geolocation from user

### LINKED ISSUE #318: Fix Spaces Nearby
Even when enabled, no space in Spaces Nearby is fetched. The problem comes from the `geolocation` property of the user that is not get correctly.

### PR DESCRIPTION
**Pull request by pyphilia**
handle null cases

closes #318

### CODE REVIEW

File: src/components/SpacesNearby.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ class SpacesNearby extends Component {
     searchQuery: prevSearchQuery,
   }) {
     const { geolocation, spaces, searchQuery } = this.props;
-    if (!geolocation.equals(prevGeolocation)) {
+    if (!geolocation?.equals(prevGeolocation)) {
```
Comment (juancarlosfarah) [inline src/components/SpacesNearby.js:71]: 🔥

**Review by juancarlosfarah — APPROVED** [review]
