### PR TITLE
fix: resolve path for app.getPath for Windows

### LINKED ISSUE #144: app.getPath() on Windows results in faulty paths
The path the function returns is of the form: `Users\kl\AppData...` whose `\` disappears afterwards. It creates bugs for example for thumbnails in Saved Spaces.

There is an issue on Electron [here ](https://github.com/electron/electron/issues/12102)which is not solved yet.

### PR DESCRIPTION
**Pull request by pyphilia**
closes #144

### CODE REVIEW

File: public/app/config/config.js [hunk 1]
```diff
@@ -26,13 +26,18 @@ const DOWNLOADABLE_MIME_TYPES = [
   'application/pdf',
 ];
 
+// resolve path for windows '\'
```
Comment (juancarlosfarah) [inline public/app/config/config.js]: I think we can use some standard function from Node `path`.

https://nodejs.org/api/path.html

File: public/app/config/config.js [hunk 2]
```diff
@@ -26,13 +26,18 @@ const DOWNLOADABLE_MIME_TYPES = [
...
+
 // categories
 const RESOURCE = 'Resource';
 const APPLICATION = 'Application';
 
-const VAR_FOLDER = `${app.getPath('userData')}/var`;
+const VAR_FOLDER = `${resolvePath(app.getPath('userData'))}/var`;
 const DATABASE_PATH = `${VAR_FOLDER}/db.json`;
-const ICON_PATH = `${app.getAppPath()}/assets/icon.png`;
+const ICON_PATH = 'app/assets/icon.png';
```
Comment (juancarlosfarah) [inline public/app/config/config.js]: Do we not need the app path here?

File: public/electron.js [hunk 3]
```diff
@@ -24,6 +24,7 @@ const {
   PRODUCT_NAME,
   DEFAULT_LANG,
   DEFAULT_DEVELOPER_MODE,
+  resolvePath,
```
Comment (juancarlosfarah) [inline public/electron.js]: Again, I think we can use Node's path functionality.

File: public/electron.js [hunk 4]
```diff
@@ -157,7 +158,8 @@ const generateMenu = () => {
           label: 'About',
           click: () => {
             openAboutWindow({
-              icon_path: ICON_PATH,
+              base_path: resolvePath(app.getAppPath()),
+              icon_path: path.join(__dirname, ICON_PATH),
```
Comment (juancarlosfarah) [inline public/electron.js]: For example, here I think Node will normalise it for Windows. But still, I'm not sure if we also need to have the appPath here instead of using `path.join`.

**Comment by juancarlosfarah** [comment]
@pyphilia, good catch! However, I think we can use some built-in Node functions (`join`, `normalize`) instead of the `resolvePath` function you created. Also, not sure why we cannot keep the `appPath` in `config` for `ICON_PATH`.

File: public/app/config/config.js (hunk 1 above)
Comment (pyphilia) [reply public/app/config/config.js]: I thought so as well, but `path.normalize` doesn't change my single `\` to `\\`

File: public/electron.js (hunk 4 above)
Comment (pyphilia) [reply public/electron.js]: I tried multiple combinaisons, but at the end once I run `yarn dist` the only solution which still provide the icon image is this one. I think it has to do with how the final files are built and where they are located then.

File: public/app/config/config.js (hunk 1 above)
Comment (juancarlosfarah) [reply public/app/config/config.js]: Do we have any docs about this problem? It seems to me that it is too generic to require a custom solution. Let's talk about this on Friday.

File: public/electron.js (hunk 4 above)
Comment (juancarlosfarah) [reply public/electron.js]: OK. I still find it a bit weird that there is not a simpler solution. Let's review it on Friday.

File: public/electron.js [hunk 5]
```diff
@@ -157,7 +158,8 @@ const generateMenu = () => {
           label: 'About',
           click: () => {
             openAboutWindow({
-              icon_path: ICON_PATH,
+              base_path: resolvePath(app.getAppPath()),
```
Comment (juancarlosfarah) [inline public/electron.js]: `// asset for icon is in the public/assets folder`
